### ISSUE TITLE
Create DNS record for proxy server

### ISSUE THREAD

**Issue by roncrivera** [roncrivera/b2b-egress-proxy#2]
```
  ProxyDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Join ['', [!Ref HostedZoneName, '.']]
      Comment: DNS name for Proxy ELB.
      Name: !Ref ProxyEndpoint
      Type: CNAME
      TTL: '60'
      ResourceRecords:
        - !GetAtt LoadBalancer.DNSName

```
